'use strict';

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

const TODO_CONSTANTS = {
  MAX_TITLE_LENGTH: 200,
};

const CATEGORY_CONSTANTS = {
  MAX_NAME_LENGTH: 50,
};

// BR-09: 카테고리 삭제 시 이 카테고리로 할일 이관
const DEFAULT_GENERAL_CATEGORY_ID = '655ebc61-df02-4b89-a969-ccbaae0cc669';

module.exports = {
  HTTP_STATUS,
  ERROR_CODES,
  TODO_CONSTANTS,
  CATEGORY_CONSTANTS,
  DEFAULT_GENERAL_CATEGORY_ID,
};
